repo = 'https://git.openwrt.org/openwrt/openwrt.git'
branch = 'master'
upload_release = true

scripts_dir = 'scripts'
feeds_dir = 'feeds'
config_dir = 'config'

[[configs]]
name = 'nanopi_r2s_base'
config = 'r2s-base'
feeds = [ 'openwrt-default.conf', 'small8.conf' ]

[[configs]]
name = 'nanopi_r2s_std'
config = 'r2s-std'
feeds = [ 'openwrt-default.conf', 'small8.conf' ]

[[configs]]
name = 'nanopi_r2s_luci'
config = 'r2s-luci'
feeds = [ 'openwrt-default.conf', 'small8.conf' ]
