repo = 'https://github.com/immortalwrt/immortalwrt'
branch = 'openwrt-21.02'
upload_release = true

scripts_dir = 'scripts'
feeds_dir = 'feeds'
config_dir = 'config'

[[configs]]
name = 'r2s_base'
config = 'nanopi-r2s-immortalwrt-base'

[[configs]]
name = 'r2s_std'
config = 'nanopi-r2s-immortalwrt-std'

[[configs]]
name = 'r2s_adbyby'
config = 'nanopi-r2s-immortalwrt-adbyby'

[[configs]]
name = 'r2s_download'
config = 'nanopi-r2s-immortalwrt-download'

[[configs]]
name = 'r2s_clash'
config = 'nanopi-r2s-immortalwrt-clash'

[[configs]]
name = 'r2s_music_plus'
config = 'nanopi-r2s-immortalwrt-music'

