repo = 'https://github.com/immortalwrt/immortalwrt.git'
branch = 'openwrt-21.02'
upload_release = true

scripts_dir = 'scripts'
feeds_dir = 'feeds'
config_dir = 'config'

[[configs]]
name = 'nanopi_r2s_base'
config = 'r2s-base'
feeds = [ 'immortalwrt.conf' ]

[[configs]]
name = 'nanopi_r2s_std'
config = 'r2s-std'
feeds = [ 'immortalwrt.conf' ]

[[configs]]
name = 'nanopi_r2s_std_dev'
config = 'r2s-std-and-dev'
feeds = [ 'immortalwrt.conf' ]
