#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#
# Update Checker
#
# Add utils for load config.toml
#

name: Update Checker

env:
  CONFIG: config.toml

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */18 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install software-properties-common
          sudo -E add-apt-repository ppa:deadsnakes/ppa
          sudo -E apt-get -qq install python3.9

          sudo -E mkdir -p ${{ env.ENVPATH }}
          sudo -E chown $USER:$GROUPS ${{ env.ENVPATH }}

          sudo ln -sf /usr/bin/python3.9 /usr/bin/python3
          python --version
          sudo -E python3 -m pip install toml pydash

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Checkout config
        run: |
          export WORKSPACE=${GITHUB_WORKSPACE}
          export ENVPATH=${{ env.ENVPATH }}

          chmod +x ${WORKSPACE}/bin/parse.sh
          source ${WORKSPACE}/bin/parse.sh

          src_repo=`get_config -t '.repo'`
          src_branch=`get_config -t '.branch'`

          set_global_env REPO_URL ${src_repo}
          set_global_env REPO_BRANCH ${src_branch}

      - name: Get Commit Hash
        id: getHash
        run: |
          git clone --depth 1 ${REPO_URL} -b ${REPO_BRANCH} .
          echo "::set-output name=commitHash::$(git rev-parse HEAD)"

      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v2
        with:
          path: .commitHash
          key: HEAD-${{ steps.getHash.outputs.commitHash }}

      - name: Save New Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

      - name: Trigger build
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          event-type: Source Code Update

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
